import {
  ImportBatch,
  AuditCheck,
  AuditAnomaly,
  AuditLog,
  PLLine,
  BSLine,
  CashFlowLine,
  KPIMetric,
  BSReconciliation,
  AccrualItem,
  PrepaymentItem,
  FixedAsset,
  JournalEntry,
} from './accountingTypes'

// ─── Import History ───────────────────────────────────────────────────────────

export const importHistory: ImportBatch[] = [
  {
    id: 'IMP-001',
    filename: 'Xero_GL_Export_May2024.csv',
    importedAt: '2024-06-01T08:15:00+10:00',
    source: 'xero',
    rowCount: 1842,
    validRows: 1835,
    errorRows: 3,
    warningRows: 4,
    status: 'completed',
    period: 'May 2024',
    mappings: [
      { sourceColumn: 'Date', targetField: 'date', dataType: 'date', sampleValue: '2024-05-31' },
      { sourceColumn: 'Account Code', targetField: 'accountCode', dataType: 'string', sampleValue: '4100' },
      { sourceColumn: 'Account Name', targetField: 'accountName', dataType: 'string', sampleValue: 'Sales Revenue' },
      { sourceColumn: 'Net Amount', targetField: 'amount', dataType: 'currency', sampleValue: '12500.00' },
      { sourceColumn: 'Reference', targetField: 'reference', dataType: 'string', sampleValue: 'INV-2024-0582' },
    ],
  },
  {
    id: 'IMP-002',
    filename: 'Payroll_May2024_KeyPay.csv',
    importedAt: '2024-06-01T09:42:00+10:00',
    source: 'csv',
    rowCount: 214,
    validRows: 214,
    errorRows: 0,
    warningRows: 0,
    status: 'completed',
    period: 'May 2024',
    mappings: [
      { sourceColumn: 'Employee ID', targetField: 'reference', dataType: 'string', sampleValue: 'EMP-0042' },
      { sourceColumn: 'Pay Date', targetField: 'date', dataType: 'date', sampleValue: '2024-05-30' },
      { sourceColumn: 'Gross Pay', targetField: 'amount', dataType: 'currency', sampleValue: '8750.00' },
      { sourceColumn: 'Cost Centre', targetField: 'costCenter', dataType: 'string', sampleValue: 'SALES' },
    ],
  },
  {
    id: 'IMP-003',
    filename: 'ANZ_Bank_Statement_May2024.csv',
    importedAt: '2024-06-02T07:30:00+10:00',
    source: 'csv',
    rowCount: 389,
    validRows: 382,
    errorRows: 0,
    warningRows: 7,
    status: 'completed',
    period: 'May 2024',
    mappings: [
      { sourceColumn: 'Transaction Date', targetField: 'date', dataType: 'date', sampleValue: '01/05/2024' },
      { sourceColumn: 'Description', targetField: 'description', dataType: 'string', sampleValue: 'BPAY PAYMENT' },
      { sourceColumn: 'Debit', targetField: 'debit', dataType: 'currency', sampleValue: '4250.00' },
      { sourceColumn: 'Credit', targetField: 'credit', dataType: 'currency', sampleValue: '0.00' },
      { sourceColumn: 'Balance', targetField: 'runningBalance', dataType: 'currency', sampleValue: '125480.50' },
    ],
  },
  {
    id: 'IMP-004',
    filename: 'Manual_Journals_May2024.xlsx',
    importedAt: '2024-06-03T14:05:00+10:00',
    source: 'manual',
    rowCount: 48,
    validRows: 44,
    errorRows: 2,
    warningRows: 2,
    status: 'completed',
    period: 'May 2024',
    mappings: [
      { sourceColumn: 'Journal Date', targetField: 'date', dataType: 'date', sampleValue: '2024-05-31' },
      { sourceColumn: 'GL Account', targetField: 'accountCode', dataType: 'string', sampleValue: '6200' },
      { sourceColumn: 'Debit Amount', targetField: 'debit', dataType: 'currency', sampleValue: '3800.00' },
      { sourceColumn: 'Credit Amount', targetField: 'credit', dataType: 'currency', sampleValue: '0.00' },
      { sourceColumn: 'Narration', targetField: 'description', dataType: 'string', sampleValue: 'May accrual - IT support' },
    ],
  },
  {
    id: 'IMP-005',
    filename: 'MYOB_AR_Ledger_May2024.csv',
    importedAt: '2024-06-02T11:20:00+10:00',
    source: 'myob',
    rowCount: 312,
    validRows: 298,
    errorRows: 8,
    warningRows: 6,
    status: 'completed',
    period: 'May 2024',
    mappings: [
      { sourceColumn: 'Inv Date', targetField: 'date', dataType: 'date', sampleValue: '15/05/2024' },
      { sourceColumn: 'Cust Code', targetField: 'reference', dataType: 'string', sampleValue: 'CUST-00142' },
      { sourceColumn: 'Inv Total', targetField: 'amount', dataType: 'currency', sampleValue: '22000.00' },
      { sourceColumn: 'Due Date', targetField: 'dueDate', dataType: 'date', sampleValue: '14/06/2024' },
    ],
  },
  {
    id: 'IMP-006',
    filename: 'FY2024_Budget_v3_Final.xlsx',
    importedAt: '2024-01-15T10:00:00+10:00',
    source: 'excel',
    rowCount: 156,
    validRows: 156,
    errorRows: 0,
    warningRows: 0,
    status: 'completed',
    period: 'FY2024',
    mappings: [
      { sourceColumn: 'Account', targetField: 'accountCode', dataType: 'string', sampleValue: '4100' },
      { sourceColumn: 'Account Description', targetField: 'accountName', dataType: 'string', sampleValue: 'Sales Revenue' },
      { sourceColumn: 'Annual Budget', targetField: 'budget', dataType: 'currency', sampleValue: '8500000.00' },
      { sourceColumn: 'Monthly Spread', targetField: 'spreadMethod', dataType: 'string', sampleValue: 'even' },
    ],
  },
]

// ─── Audit Checks ─────────────────────────────────────────────────────────────

export const auditChecks: AuditCheck[] = [
  {
    id: 'AC-001',
    category: 'completeness',
    name: 'All GL Accounts Mapped',
    description: 'Verify every imported GL account code exists in the chart of accounts',
    status: 'pass',
    count: 248,
    severity: 'critical',
  },
  {
    id: 'AC-002',
    category: 'completeness',
    name: 'Missing Transaction References',
    description: 'Identify transactions without a reference number or invoice number',
    status: 'warning',
    count: 14,
    amount: 38420.5,
    severity: 'medium',
  },
  {
    id: 'AC-003',
    category: 'accuracy',
    name: 'Trial Balance Check',
    description: 'Total debits must equal total credits across all posted journals',
    status: 'pass',
    count: 1842,
    amount: 0,
    severity: 'critical',
  },
  {
    id: 'AC-004',
    category: 'accuracy',
    name: 'Duplicate Transaction Detection',
    description: 'Scan for transactions with identical amount, date and description within 3 days',
    status: 'fail',
    count: 3,
    amount: 14750.0,
    severity: 'high',
  },
  {
    id: 'AC-005',
    category: 'validity',
    name: 'GST Coding Validation',
    description: 'Ensure GST codes are consistent with account type and supplier registration',
    status: 'warning',
    count: 8,
    amount: 9280.0,
    severity: 'high',
  },
  {
    id: 'AC-006',
    category: 'validity',
    name: 'Negative Balance Accounts',
    description: 'Flag asset accounts carrying unexpected credit balances',
    status: 'fail',
    count: 2,
    amount: 4150.75,
    severity: 'medium',
  },
  {
    id: 'AC-007',
    category: 'consistency',
    name: 'Intercompany Eliminations',
    description: 'Verify intercompany receivables and payables net to zero',
    status: 'pass',
    count: 6,
    amount: 0,
    severity: 'high',
  },
  {
    id: 'AC-008',
    category: 'consistency',
    name: 'Bank Reconciliation Match',
    description: 'GL cash balance must reconcile to bank statement closing balance',
    status: 'pass',
    count: 3,
    amount: 0,
    severity: 'critical',
  },
  {
    id: 'AC-009',
    category: 'consistency',
    name: 'Accrual Reversal Postings',
    description: 'All April 2024 accruals must have corresponding May 2024 reversals',
    status: 'warning',
    count: 2,
    amount: 6800.0,
    severity: 'medium',
  },
  {
    id: 'AC-010',
    category: 'timeliness',
    name: 'Cut-off Testing - Revenue',
    description: 'Revenue recognised in May must relate to goods/services delivered before 31 May 2024',
    status: 'pass',
    count: 42,
    amount: 128500.0,
    severity: 'high',
  },
  {
    id: 'AC-011',
    category: 'timeliness',
    name: 'Late Journal Postings',
    description: 'Identify journals posted after the period close date (5 business days)',
    status: 'fail',
    count: 5,
    amount: 22340.0,
    severity: 'low',
  },
  {
    id: 'AC-012',
    category: 'completeness',
    name: 'Fixed Asset Register Reconciliation',
    description: 'FA register net book value must agree to GL fixed asset accounts',
    status: 'pass',
    count: 47,
    amount: 1284500.0,
    severity: 'high',
  },
]

// ─── Audit Anomalies ──────────────────────────────────────────────────────────

export const auditAnomalies: AuditAnomaly[] = [
  {
    id: 'AN-001',
    date: '2024-05-14',
    account: 'Office Supplies & Stationery',
    accountCode: '6310',
    description: 'Staples Australia - office supplies purchase',
    amount: 2840.0,
    expectedRange: { min: 100, max: 1500 },
    flag: 'outlier',
    status: 'open',
    assignedTo: 'Sarah Chen',
    detectedAt: '2024-06-01T08:22:00+10:00',
  },
  {
    id: 'AN-002',
    date: '2024-05-22',
    account: 'Travel & Entertainment',
    accountCode: '6420',
    description: 'Flight Centre - domestic airfares',
    amount: 4750.0,
    expectedRange: { min: 0, max: 3000 },
    flag: 'outlier',
    status: 'reviewed',
    assignedTo: 'James Hartley',
    notes: 'Confirmed - executive team offsite in Perth. CEO approved.',
    detectedAt: '2024-06-01T08:22:00+10:00',
  },
  {
    id: 'AN-003',
    date: '2024-05-08',
    account: 'Advertising & Marketing',
    accountCode: '6510',
    description: 'Google Ads - digital campaign spend',
    amount: 8500.0,
    expectedRange: { min: 5000, max: 7500 },
    flag: 'outlier',
    status: 'open',
    detectedAt: '2024-06-01T08:22:00+10:00',
  },
  {
    id: 'AN-004',
    date: '2024-05-31',
    account: 'Accounts Payable - Trade',
    accountCode: '2100',
    description: 'Advance Building Services - cleaning invoice INV-4821',
    amount: 6250.0,
    expectedRange: { min: 5800, max: 6400 },
    flag: 'duplicate',
    status: 'open',
    assignedTo: 'Sarah Chen',
    notes: 'Possible duplicate of INV-4820 posted 29 May. Investigating.',
    detectedAt: '2024-06-02T09:15:00+10:00',
  },
  {
    id: 'AN-005',
    date: '2024-05-01',
    account: 'Interest Income',
    accountCode: '8100',
    description: 'ANZ Term Deposit - interest credit',
    amount: 0,
    expectedRange: { min: 1800, max: 2500 },
    flag: 'missing',
    status: 'open',
    assignedTo: 'James Hartley',
    notes: 'No interest receipt recorded for May. ANZ statement confirms $2,140 earned.',
    detectedAt: '2024-06-01T08:22:00+10:00',
  },
  {
    id: 'AN-006',
    date: '2024-05-31',
    account: 'Professional Services',
    accountCode: '6210',
    description: 'Deloitte - audit services Q4 invoice',
    amount: 55000.0,
    expectedRange: { min: 15000, max: 25000 },
    flag: 'outlier',
    status: 'reviewed',
    assignedTo: 'Olivia Nguyen',
    notes: 'Q4 annual audit invoice includes catch-up fees. Approved by CFO.',
    detectedAt: '2024-06-01T08:22:00+10:00',
  },
  {
    id: 'AN-007',
    date: '2024-05-29',
    account: 'Wages & Salaries',
    accountCode: '6100',
    description: 'Payroll run - unusual mid-cycle payment',
    amount: 18500.0,
    expectedRange: { min: 0, max: 5000 },
    flag: 'unusual_timing',
    status: 'resolved',
    assignedTo: 'Sarah Chen',
    notes: 'Off-cycle payment for redundancy settlement - HR confirmed and documented.',
    detectedAt: '2024-06-01T08:22:00+10:00',
  },
  {
    id: 'AN-008',
    date: '2024-05-15',
    account: 'Repairs & Maintenance',
    accountCode: '6350',
    description: 'Vendor invoice - no supplier name or ABN recorded',
    amount: 3200.0,
    expectedRange: { min: 0, max: 5000 },
    flag: 'missing',
    status: 'open',
    assignedTo: 'Olivia Nguyen',
    detectedAt: '2024-06-02T09:15:00+10:00',
  },
]

// ─── Audit Log ────────────────────────────────────────────────────────────────

export const auditLog: AuditLog[] = [
  {
    id: 'LOG-001',
    action: 'Data Import',
    user: 'sarah.chen@meridianfinance.com.au',
    timestamp: '2024-06-01T08:15:22+10:00',
    module: 'Import',
    details: 'Imported Xero GL Export May 2024 - 1842 rows processed',
    outcome: 'success',
  },
  {
    id: 'LOG-002',
    action: 'Audit Run',
    user: 'sarah.chen@meridianfinance.com.au',
    timestamp: '2024-06-01T08:22:05+10:00',
    module: 'Audit',
    details: 'Full audit suite executed - 12 checks, 3 failures detected',
    outcome: 'warning',
  },
  {
    id: 'LOG-003',
    action: 'Journal Posted',
    user: 'james.hartley@meridianfinance.com.au',
    timestamp: '2024-06-01T09:05:44+10:00',
    module: 'Journals',
    details: 'Posted JNL-2024-0145 - May accruals bundle ($48,320 Dr)',
    outcome: 'success',
  },
  {
    id: 'LOG-004',
    action: 'Anomaly Reviewed',
    user: 'james.hartley@meridianfinance.com.au',
    timestamp: '2024-06-01T10:30:18+10:00',
    module: 'Audit',
    details: 'AN-002 marked as reviewed - Travel outlier explained by Perth offsite',
    outcome: 'success',
  },
  {
    id: 'LOG-005',
    action: 'Reconciliation Updated',
    user: 'olivia.nguyen@meridianfinance.com.au',
    timestamp: '2024-06-02T08:45:00+10:00',
    module: 'Reconciliations',
    details: 'Trade Receivables reconciliation updated - status changed to In Progress',
    outcome: 'success',
  },
  {
    id: 'LOG-006',
    action: 'Data Import',
    user: 'olivia.nguyen@meridianfinance.com.au',
    timestamp: '2024-06-02T11:20:33+10:00',
    module: 'Import',
    details: 'Imported MYOB AR Ledger May 2024 - 8 row errors skipped',
    outcome: 'warning',
  },
  {
    id: 'LOG-007',
    action: 'Journal Approved',
    user: 'michael.park@meridianfinance.com.au',
    timestamp: '2024-06-03T09:12:00+10:00',
    module: 'Journals',
    details: 'Approved JNL-2024-0146 - Depreciation journal for May 2024',
    outcome: 'success',
  },
  {
    id: 'LOG-008',
    action: 'Reconciliation Signed Off',
    user: 'michael.park@meridianfinance.com.au',
    timestamp: '2024-06-03T14:30:00+10:00',
    module: 'Reconciliations',
    details: 'Bank reconciliation ANZ Operating Account signed off as Reconciled',
    outcome: 'success',
  },
  {
    id: 'LOG-009',
    action: 'Import Error',
    user: 'sarah.chen@meridianfinance.com.au',
    timestamp: '2024-06-03T15:05:22+10:00',
    module: 'Import',
    details: 'Manual journals import failed - 2 rows with unmatched account codes',
    outcome: 'error',
  },
  {
    id: 'LOG-010',
    action: 'Report Generated',
    user: 'michael.park@meridianfinance.com.au',
    timestamp: '2024-06-04T08:00:00+10:00',
    module: 'Analysis',
    details: 'May 2024 Management Pack generated and distributed to board',
    outcome: 'success',
  },
]

// ─── P&L Lines ────────────────────────────────────────────────────────────────

export const plLines: PLLine[] = [
  // Revenue
  {
    code: '4100',
    name: 'Sales Revenue - Products',
    type: 'revenue',
    actual: 512840,
    budget: 490000,
    priorYear: 468200,
    ytdActual: 2541600,
    ytdBudget: 2450000,
    indent: 1,
  },
  {
    code: '4200',
    name: 'Sales Revenue - Services',
    type: 'revenue',
    actual: 218650,
    budget: 210000,
    priorYear: 195400,
    ytdActual: 1082300,
    ytdBudget: 1050000,
    indent: 1,
  },
  {
    code: '4300',
    name: 'Licence & Subscription Revenue',
    type: 'revenue',
    actual: 85200,
    budget: 80000,
    priorYear: 72000,
    ytdActual: 421000,
    ytdBudget: 400000,
    indent: 1,
  },
  {
    code: '4400',
    name: 'Other Income',
    type: 'revenue',
    actual: 12480,
    budget: 10000,
    priorYear: 9800,
    ytdActual: 54200,
    ytdBudget: 50000,
    indent: 1,
  },
  {
    code: 'REV-TOTAL',
    name: 'Total Revenue',
    type: 'subtotal',
    actual: 829170,
    budget: 790000,
    priorYear: 745400,
    ytdActual: 4099100,
    ytdBudget: 3950000,
    isSubtotal: true,
    indent: 0,
  },
  // COGS
  {
    code: '5100',
    name: 'Cost of Goods Sold - Products',
    type: 'cogs',
    actual: 281062,
    budget: 269500,
    priorYear: 257510,
    ytdActual: 1397880,
    ytdBudget: 1347500,
    indent: 1,
  },
  {
    code: '5200',
    name: 'Direct Labour',
    type: 'cogs',
    actual: 74628,
    budget: 73500,
    priorYear: 68420,
    ytdActual: 368140,
    ytdBudget: 367500,
    indent: 1,
  },
  {
    code: '5300',
    name: 'Freight & Logistics',
    type: 'cogs',
    actual: 24875,
    budget: 23000,
    priorYear: 21300,
    ytdActual: 121450,
    ytdBudget: 115000,
    indent: 1,
  },
  {
    code: 'COGS-TOTAL',
    name: 'Total Cost of Goods Sold',
    type: 'subtotal',
    actual: 380565,
    budget: 366000,
    priorYear: 347230,
    ytdActual: 1887470,
    ytdBudget: 1830000,
    isSubtotal: true,
    indent: 0,
  },
  // Gross Profit
  {
    code: 'GP',
    name: 'Gross Profit',
    type: 'gross_profit',
    actual: 448605,
    budget: 424000,
    priorYear: 398170,
    ytdActual: 2211630,
    ytdBudget: 2120000,
    isSubtotal: true,
    indent: 0,
  },
  // Operating Expenses
  {
    code: '6100',
    name: 'Wages & Salaries',
    type: 'opex',
    actual: 162840,
    budget: 155000,
    priorYear: 148200,
    ytdActual: 802400,
    ytdBudget: 775000,
    indent: 1,
  },
  {
    code: '6110',
    name: 'Superannuation',
    type: 'opex',
    actual: 17913,
    budget: 17050,
    priorYear: 16302,
    ytdActual: 88264,
    ytdBudget: 85250,
    indent: 1,
  },
  {
    code: '6120',
    name: 'Staff On-costs & Leave',
    type: 'opex',
    actual: 8142,
    budget: 7750,
    priorYear: 7200,
    ytdActual: 40710,
    ytdBudget: 38750,
    indent: 1,
  },
  {
    code: '6200',
    name: 'Rent & Occupancy',
    type: 'opex',
    actual: 28500,
    budget: 28500,
    priorYear: 27000,
    ytdActual: 142500,
    ytdBudget: 142500,
    indent: 1,
  },
  {
    code: '6210',
    name: 'Professional Services',
    type: 'opex',
    actual: 68400,
    budget: 22000,
    priorYear: 19800,
    ytdActual: 131200,
    ytdBudget: 110000,
    indent: 1,
  },
  {
    code: '6220',
    name: 'IT & Software Subscriptions',
    type: 'opex',
    actual: 18650,
    budget: 18000,
    priorYear: 15600,
    ytdActual: 92150,
    ytdBudget: 90000,
    indent: 1,
  },
  {
    code: '6310',
    name: 'Office Supplies & Stationery',
    type: 'opex',
    actual: 4820,
    budget: 2500,
    priorYear: 2200,
    ytdActual: 14680,
    ytdBudget: 12500,
    indent: 1,
  },
  {
    code: '6350',
    name: 'Repairs & Maintenance',
    type: 'opex',
    actual: 9640,
    budget: 8000,
    priorYear: 7400,
    ytdActual: 42180,
    ytdBudget: 40000,
    indent: 1,
  },
  {
    code: '6420',
    name: 'Travel & Entertainment',
    type: 'opex',
    actual: 12380,
    budget: 8500,
    priorYear: 7800,
    ytdActual: 48920,
    ytdBudget: 42500,
    indent: 1,
  },
  {
    code: '6510',
    name: 'Advertising & Marketing',
    type: 'opex',
    actual: 22400,
    budget: 20000,
    priorYear: 18500,
    ytdActual: 108600,
    ytdBudget: 100000,
    indent: 1,
  },
  {
    code: '6600',
    name: 'Insurance',
    type: 'opex',
    actual: 8250,
    budget: 8250,
    priorYear: 7500,
    ytdActual: 41250,
    ytdBudget: 41250,
    indent: 1,
  },
  {
    code: '6700',
    name: 'Utilities',
    type: 'opex',
    actual: 4180,
    budget: 4000,
    priorYear: 3750,
    ytdActual: 20640,
    ytdBudget: 20000,
    indent: 1,
  },
  {
    code: 'OPEX-TOTAL',
    name: 'Total Operating Expenses',
    type: 'subtotal',
    actual: 366115,
    budget: 299550,
    priorYear: 281252,
    ytdActual: 1573494,
    ytdBudget: 1497750,
    isSubtotal: true,
    indent: 0,
  },
  // EBITDA
  {
    code: 'EBITDA',
    name: 'EBITDA',
    type: 'ebitda',
    actual: 82490,
    budget: 124450,
    priorYear: 116918,
    ytdActual: 638136,
    ytdBudget: 622250,
    isSubtotal: true,
    indent: 0,
  },
  {
    code: '7100',
    name: 'Depreciation & Amortisation',
    type: 'opex',
    actual: 14280,
    budget: 14000,
    priorYear: 12800,
    ytdActual: 70980,
    ytdBudget: 70000,
    indent: 1,
  },
  // EBIT
  {
    code: 'EBIT',
    name: 'EBIT',
    type: 'ebit',
    actual: 68210,
    budget: 110450,
    priorYear: 104118,
    ytdActual: 567156,
    ytdBudget: 552250,
    isSubtotal: true,
    indent: 0,
  },
  {
    code: '8000',
    name: 'Interest Expense',
    type: 'opex',
    actual: 6840,
    budget: 6500,
    priorYear: 7200,
    ytdActual: 33480,
    ytdBudget: 32500,
    indent: 1,
  },
  {
    code: '8100',
    name: 'Interest Income',
    type: 'revenue',
    actual: 2140,
    budget: 1800,
    priorYear: 1200,
    ytdActual: 9850,
    ytdBudget: 9000,
    indent: 1,
  },
  {
    code: '9000',
    name: 'Income Tax Expense',
    type: 'opex',
    actual: 19053,
    budget: 31425,
    priorYear: 29076,
    ytdActual: 162885,
    ytdBudget: 156825,
    indent: 1,
  },
  // Net Profit
  {
    code: 'NP',
    name: 'Net Profit After Tax',
    type: 'net_profit',
    actual: 44457,
    budget: 74325,
    priorYear: 69042,
    ytdActual: 380641,
    ytdBudget: 371925,
    isSubtotal: true,
    indent: 0,
  },
]

// ─── Balance Sheet Lines ──────────────────────────────────────────────────────

export const bsLines: BSLine[] = [
  // Current Assets
  {
    code: '1000',
    name: 'Cash at Bank - ANZ Operating',
    category: 'current_assets',
    actual: 284620,
    prior: 241380,
    indent: 1,
  },
  {
    code: '1010',
    name: 'Cash at Bank - ANZ Payroll',
    category: 'current_assets',
    actual: 48200,
    prior: 52400,
    indent: 1,
  },
  {
    code: '1020',
    name: 'ANZ Term Deposit (90-day)',
    category: 'current_assets',
    actual: 150000,
    prior: 150000,
    indent: 1,
  },
  {
    code: '1100',
    name: 'Trade Receivables',
    category: 'current_assets',
    actual: 412840,
    prior: 378620,
    indent: 1,
  },
  {
    code: '1110',
    name: 'Less: Provision for Doubtful Debts',
    category: 'current_assets',
    actual: -18500,
    prior: -16200,
    indent: 2,
  },
  {
    code: '1120',
    name: 'GST Receivable',
    category: 'current_assets',
    actual: 38640,
    prior: 34120,
    indent: 1,
  },
  {
    code: '1200',
    name: 'Inventory - Finished Goods',
    category: 'current_assets',
    actual: 186420,
    prior: 194800,
    indent: 1,
  },
  {
    code: '1210',
    name: 'Inventory - Raw Materials',
    category: 'current_assets',
    actual: 64300,
    prior: 58900,
    indent: 1,
  },
  {
    code: '1300',
    name: 'Prepayments',
    category: 'current_assets',
    actual: 84620,
    prior: 92140,
    indent: 1,
  },
  {
    code: '1310',
    name: 'Other Current Assets',
    category: 'current_assets',
    actual: 12480,
    prior: 9800,
    indent: 1,
  },
  {
    code: 'CA-TOTAL',
    name: 'Total Current Assets',
    category: 'current_assets',
    actual: 1263620,
    prior: 1195960,
    isSubtotal: true,
    indent: 0,
  },
  // Non-Current Assets
  {
    code: '1500',
    name: 'Property, Plant & Equipment (Cost)',
    category: 'non_current_assets',
    actual: 1842400,
    prior: 1798600,
    indent: 1,
  },
  {
    code: '1510',
    name: 'Less: Accumulated Depreciation',
    category: 'non_current_assets',
    actual: -557900,
    prior: -543620,
    indent: 2,
  },
  {
    code: '1520',
    name: 'Right-of-Use Assets',
    category: 'non_current_assets',
    actual: 312000,
    prior: 340800,
    indent: 1,
  },
  {
    code: '1600',
    name: 'Intangible Assets - Software',
    category: 'non_current_assets',
    actual: 128400,
    prior: 138200,
    indent: 1,
  },
  {
    code: '1610',
    name: 'Goodwill',
    category: 'non_current_assets',
    actual: 480000,
    prior: 480000,
    indent: 1,
  },
  {
    code: '1700',
    name: 'Deferred Tax Asset',
    category: 'non_current_assets',
    actual: 42800,
    prior: 38600,
    indent: 1,
  },
  {
    code: 'NCA-TOTAL',
    name: 'Total Non-Current Assets',
    category: 'non_current_assets',
    actual: 2247700,
    prior: 2252580,
    isSubtotal: true,
    indent: 0,
  },
  {
    code: 'ASSETS-TOTAL',
    name: 'Total Assets',
    category: 'non_current_assets',
    actual: 3511320,
    prior: 3448540,
    isSubtotal: true,
    indent: 0,
  },
  // Current Liabilities
  {
    code: '2100',
    name: 'Trade Payables',
    category: 'current_liabilities',
    actual: 198640,
    prior: 182400,
    indent: 1,
  },
  {
    code: '2110',
    name: 'Accrued Liabilities',
    category: 'current_liabilities',
    actual: 124800,
    prior: 118200,
    indent: 1,
  },
  {
    code: '2120',
    name: 'GST Payable',
    category: 'current_liabilities',
    actual: 28420,
    prior: 24600,
    indent: 1,
  },
  {
    code: '2130',
    name: 'PAYG Withholding Payable',
    category: 'current_liabilities',
    actual: 38400,
    prior: 36800,
    indent: 1,
  },
  {
    code: '2140',
    name: 'Superannuation Payable',
    category: 'current_liabilities',
    actual: 17913,
    prior: 17050,
    indent: 1,
  },
  {
    code: '2150',
    name: 'Employee Leave Provisions',
    category: 'current_liabilities',
    actual: 84200,
    prior: 79600,
    indent: 1,
  },
  {
    code: '2200',
    name: 'Income Tax Payable',
    category: 'current_liabilities',
    actual: 42800,
    prior: 38400,
    indent: 1,
  },
  {
    code: '2300',
    name: 'Current Portion - Lease Liabilities',
    category: 'current_liabilities',
    actual: 108000,
    prior: 108000,
    indent: 1,
  },
  {
    code: '2400',
    name: 'Short-term Bank Facility',
    category: 'current_liabilities',
    actual: 80000,
    prior: 100000,
    indent: 1,
  },
  {
    code: 'CL-TOTAL',
    name: 'Total Current Liabilities',
    category: 'current_liabilities',
    actual: 723173,
    prior: 705050,
    isSubtotal: true,
    indent: 0,
  },
  // Non-Current Liabilities
  {
    code: '2600',
    name: 'Term Loan - ANZ',
    category: 'non_current_liabilities',
    actual: 620000,
    prior: 680000,
    indent: 1,
  },
  {
    code: '2610',
    name: 'Non-Current Lease Liabilities',
    category: 'non_current_liabilities',
    actual: 204000,
    prior: 232800,
    indent: 1,
  },
  {
    code: '2700',
    name: 'Deferred Tax Liability',
    category: 'non_current_liabilities',
    actual: 28400,
    prior: 24200,
    indent: 1,
  },
  {
    code: '2800',
    name: 'Employee Long Service Leave',
    category: 'non_current_liabilities',
    actual: 38600,
    prior: 35400,
    indent: 1,
  },
  {
    code: 'NCL-TOTAL',
    name: 'Total Non-Current Liabilities',
    category: 'non_current_liabilities',
    actual: 891000,
    prior: 972400,
    isSubtotal: true,
    indent: 0,
  },
  {
    code: 'LIAB-TOTAL',
    name: 'Total Liabilities',
    category: 'non_current_liabilities',
    actual: 1614173,
    prior: 1677450,
    isSubtotal: true,
    indent: 0,
  },
  // Equity
  {
    code: '3000',
    name: 'Share Capital',
    category: 'equity',
    actual: 800000,
    prior: 800000,
    indent: 1,
  },
  {
    code: '3100',
    name: 'Retained Earnings (Opening)',
    category: 'equity',
    actual: 716449,
    prior: 587249,
    indent: 1,
  },
  {
    code: '3200',
    name: 'Current Year Profit',
    category: 'equity',
    actual: 380641,
    prior: 383750,
    indent: 1,
  },
  {
    code: '3300',
    name: 'Dividends Paid',
    category: 'equity',
    actual: 0,
    prior: -100000,
    indent: 1,
  },
  {
    code: 'EQ-TOTAL',
    name: 'Total Equity',
    category: 'equity',
    actual: 1897090,
    prior: 1671090,
    isSubtotal: true,
    indent: 0,
  },
  {
    code: 'LIAB-EQ-TOTAL',
    name: 'Total Liabilities & Equity',
    category: 'equity',
    actual: 3511263,
    prior: 3348540,
    isSubtotal: true,
    indent: 0,
  },
]

// ─── Cash Flow Lines ──────────────────────────────────────────────────────────

export const cashFlowLines: CashFlowLine[] = [
  // Operating
  { name: 'Net Profit After Tax', category: 'operating', actual: 44457, prior: 69042 },
  { name: 'Add: Depreciation & Amortisation', category: 'operating', actual: 14280, prior: 12800 },
  { name: 'Add: Amortisation of Right-of-Use Assets', category: 'operating', actual: 28800, prior: 28800 },
  { name: 'Decrease/(Increase) in Trade Receivables', category: 'operating', actual: -34220, prior: 18400 },
  { name: 'Decrease/(Increase) in Inventory', category: 'operating', actual: 2980, prior: -12600 },
  { name: 'Decrease/(Increase) in Prepayments', category: 'operating', actual: 7520, prior: -4200 },
  { name: 'Increase/(Decrease) in Trade Payables', category: 'operating', actual: 16240, prior: 8620 },
  { name: 'Increase/(Decrease) in Accrued Liabilities', category: 'operating', actual: 6600, prior: 3800 },
  { name: 'Increase/(Decrease) in Tax Payable', category: 'operating', actual: 4400, prior: 2840 },
  { name: 'Net Cash from Operating Activities', category: 'operating', actual: 91057, prior: 127502, isSubtotal: true },
  // Investing
  { name: 'Purchase of Property, Plant & Equipment', category: 'investing', actual: -43800, prior: -68200 },
  { name: 'Purchase of Intangible Assets', category: 'investing', actual: 0, prior: -15000 },
  { name: 'Proceeds from Asset Disposal', category: 'investing', actual: 0, prior: 8400 },
  { name: 'Movement in Term Deposits', category: 'investing', actual: 0, prior: -50000 },
  { name: 'Net Cash from Investing Activities', category: 'investing', actual: -43800, prior: -124800, isSubtotal: true },
  // Financing
  { name: 'Repayment of Term Loan', category: 'financing', actual: -60000, prior: -60000 },
  { name: 'Repayment of Lease Liabilities', category: 'financing', actual: -28800, prior: -28800 },
  { name: 'Dividends Paid', category: 'financing', actual: 0, prior: 0 },
  { name: 'Net Proceeds from Short-term Facility', category: 'financing', actual: -20000, prior: 20000 },
  { name: 'Net Cash from Financing Activities', category: 'financing', actual: -108800, prior: -68800, isSubtotal: true },
  { name: 'Net Movement in Cash', category: 'operating', actual: -61543, prior: -66098, isSubtotal: true },
  { name: 'Opening Cash Balance', category: 'operating', actual: 394363, prior: 398240 },
  { name: 'Closing Cash Balance', category: 'operating', actual: 332820, prior: 332142, isSubtotal: true },
]

// ─── KPI Metrics ──────────────────────────────────────────────────────────────

export const kpiMetrics: KPIMetric[] = [
  {
    name: 'Gross Margin %',
    value: 54.1,
    unit: 'percent',
    prior: 53.4,
    benchmark: 52.0,
    trend: 'up',
    good: true,
  },
  {
    name: 'EBITDA Margin %',
    value: 9.9,
    unit: 'percent',
    prior: 15.7,
    benchmark: 14.0,
    trend: 'down',
    good: false,
  },
  {
    name: 'Net Profit Margin %',
    value: 5.4,
    unit: 'percent',
    prior: 9.3,
    benchmark: 8.0,
    trend: 'down',
    good: false,
  },
  {
    name: 'Current Ratio',
    value: 1.75,
    unit: 'ratio',
    prior: 1.70,
    benchmark: 1.5,
    trend: 'up',
    good: true,
  },
  {
    name: 'Quick Ratio',
    value: 1.02,
    unit: 'ratio',
    prior: 0.98,
    benchmark: 1.0,
    trend: 'up',
    good: true,
  },
  {
    name: 'Days Sales Outstanding (DSO)',
    value: 45.2,
    unit: 'days',
    prior: 46.8,
    benchmark: 42.0,
    trend: 'down',
    good: true,
  },
  {
    name: 'Days Payable Outstanding (DPO)',
    value: 38.4,
    unit: 'days',
    prior: 36.2,
    benchmark: 35.0,
    trend: 'up',
    good: true,
  },
  {
    name: 'Inventory Days',
    value: 52.8,
    unit: 'days',
    prior: 58.4,
    benchmark: 50.0,
    trend: 'down',
    good: true,
  },
  {
    name: 'Debt / Equity Ratio',
    value: 0.37,
    unit: 'ratio',
    prior: 0.47,
    benchmark: 0.5,
    trend: 'down',
    good: true,
  },
  {
    name: 'Return on Capital Employed (ROCE)',
    value: 18.4,
    unit: 'percent',
    prior: 22.1,
    benchmark: 20.0,
    trend: 'down',
    good: false,
  },
]

// ─── Balance Sheet Reconciliations ────────────────────────────────────────────

export const bsReconciliations: BSReconciliation[] = [
  {
    id: 'REC-001',
    accountCode: '1100',
    accountName: 'Trade Receivables',
    category: 'current_assets',
    openingBalance: 378620,
    closingBalance: 412840,
    movements: [
      {
        id: 'MOV-001-1',
        date: '2024-05-31',
        description: 'Invoices issued during May 2024',
        reference: 'XERO-AR-MAY24',
        type: 'addition',
        debit: 829170,
        credit: 0,
        runningBalance: 1207790,
      },
      {
        id: 'MOV-001-2',
        date: '2024-05-31',
        description: 'Cash receipts from customers',
        reference: 'ANZ-MAY24',
        type: 'payment',
        debit: 0,
        credit: 794950,
        runningBalance: 412840,
      },
    ],
    variance: 0,
    status: 'in_progress',
    lastUpdated: '2024-06-02T08:45:00+10:00',
    preparedBy: 'Olivia Nguyen',
  },
  {
    id: 'REC-002',
    accountCode: '2100',
    accountName: 'Trade Payables',
    category: 'current_liabilities',
    openingBalance: 182400,
    closingBalance: 198640,
    movements: [
      {
        id: 'MOV-002-1',
        date: '2024-05-31',
        description: 'Supplier invoices received in May 2024',
        reference: 'AP-MAY24',
        type: 'addition',
        debit: 0,
        credit: 380565,
        runningBalance: 562965,
      },
      {
        id: 'MOV-002-2',
        date: '2024-05-31',
        description: 'Payments made to suppliers',
        reference: 'ANZ-PAY-MAY24',
        type: 'payment',
        debit: 364325,
        credit: 0,
        runningBalance: 198640,
      },
    ],
    variance: 0,
    status: 'reconciled',
    lastUpdated: '2024-06-03T10:00:00+10:00',
    preparedBy: 'Sarah Chen',
    reviewedBy: 'Michael Park',
  },
  {
    id: 'REC-003',
    accountCode: '1300',
    accountName: 'Prepayments',
    category: 'current_assets',
    openingBalance: 92140,
    closingBalance: 84620,
    movements: [
      {
        id: 'MOV-003-1',
        date: '2024-05-01',
        description: 'Monthly amortisation of prepaid insurance',
        reference: 'JNL-2024-0140',
        type: 'adjustment',
        debit: 0,
        credit: 4125,
        runningBalance: 88015,
      },
      {
        id: 'MOV-003-2',
        date: '2024-05-01',
        description: 'Monthly amortisation of prepaid rent',
        reference: 'JNL-2024-0140',
        type: 'adjustment',
        debit: 0,
        credit: 2850,
        runningBalance: 85165,
      },
      {
        id: 'MOV-003-3',
        date: '2024-05-01',
        description: 'Monthly amortisation of software subscriptions',
        reference: 'JNL-2024-0140',
        type: 'adjustment',
        debit: 0,
        credit: 545,
        runningBalance: 84620,
      },
    ],
    variance: 0,
    status: 'reconciled',
    lastUpdated: '2024-06-03T11:30:00+10:00',
    preparedBy: 'Sarah Chen',
    reviewedBy: 'Michael Park',
    supportingSchedule: 'Prepayment_Schedule_May2024.xlsx',
  },
  {
    id: 'REC-004',
    accountCode: '2110',
    accountName: 'Accrued Liabilities',
    category: 'current_liabilities',
    openingBalance: 118200,
    closingBalance: 124800,
    movements: [
      {
        id: 'MOV-004-1',
        date: '2024-05-01',
        description: 'Reversal of April accruals',
        reference: 'JNL-2024-0138',
        type: 'reversal',
        debit: 118200,
        credit: 0,
        runningBalance: 0,
      },
      {
        id: 'MOV-004-2',
        date: '2024-05-31',
        description: 'May accruals - professional services, utilities, IT',
        reference: 'JNL-2024-0145',
        type: 'accrual',
        debit: 0,
        credit: 124800,
        runningBalance: 124800,
      },
    ],
    variance: 0,
    status: 'reconciled',
    lastUpdated: '2024-06-03T14:00:00+10:00',
    preparedBy: 'James Hartley',
    reviewedBy: 'Michael Park',
    supportingSchedule: 'Accruals_Schedule_May2024.xlsx',
  },
  {
    id: 'REC-005',
    accountCode: '1500',
    accountName: 'Fixed Assets - Net Book Value',
    category: 'non_current_assets',
    openingBalance: 1254980,
    closingBalance: 1284500,
    movements: [
      {
        id: 'MOV-005-1',
        date: '2024-05-10',
        description: 'Acquisition - Production Line Equipment',
        reference: 'PO-2024-0318',
        type: 'addition',
        debit: 43800,
        credit: 0,
        runningBalance: 1298780,
      },
      {
        id: 'MOV-005-2',
        date: '2024-05-31',
        description: 'Monthly depreciation charge',
        reference: 'JNL-2024-0146',
        type: 'adjustment',
        debit: 0,
        credit: 14280,
        runningBalance: 1284500,
      },
    ],
    variance: 0,
    status: 'reconciled',
    lastUpdated: '2024-06-03T09:30:00+10:00',
    preparedBy: 'Olivia Nguyen',
    reviewedBy: 'Michael Park',
    supportingSchedule: 'Fixed_Asset_Register_May2024.xlsx',
  },
  {
    id: 'REC-006',
    accountCode: '3100',
    accountName: 'Retained Earnings',
    category: 'equity',
    openingBalance: 716449,
    closingBalance: 760906,
    movements: [
      {
        id: 'MOV-006-1',
        date: '2024-05-31',
        description: 'Net profit for May 2024',
        reference: 'AUTO-CLOSE-MAY24',
        type: 'adjustment',
        debit: 0,
        credit: 44457,
        runningBalance: 760906,
      },
    ],
    variance: 0,
    status: 'reconciled',
    lastUpdated: '2024-06-04T08:00:00+10:00',
    preparedBy: 'James Hartley',
    reviewedBy: 'Michael Park',
  },
  {
    id: 'REC-007',
    accountCode: '1000',
    accountName: 'Bank - ANZ Operating Account',
    category: 'current_assets',
    openingBalance: 241380,
    closingBalance: 284620,
    movements: [
      {
        id: 'MOV-007-1',
        date: '2024-05-31',
        description: 'Total receipts per bank statement',
        reference: 'ANZ-STMT-MAY24',
        type: 'addition',
        debit: 837390,
        credit: 0,
        runningBalance: 1078770,
      },
      {
        id: 'MOV-007-2',
        date: '2024-05-31',
        description: 'Total payments per bank statement',
        reference: 'ANZ-STMT-MAY24',
        type: 'payment',
        debit: 0,
        credit: 794150,
        runningBalance: 284620,
      },
    ],
    variance: 0,
    status: 'reconciled',
    lastUpdated: '2024-06-03T14:30:00+10:00',
    preparedBy: 'Sarah Chen',
    reviewedBy: 'Michael Park',
    supportingSchedule: 'Bank_Rec_ANZ_May2024.xlsx',
  },
  {
    id: 'REC-008',
    accountCode: '1200',
    accountName: 'Inventory - Finished Goods',
    category: 'current_assets',
    openingBalance: 194800,
    closingBalance: 186420,
    movements: [
      {
        id: 'MOV-008-1',
        date: '2024-05-31',
        description: 'Goods received into stock',
        reference: 'GRN-MAY24',
        type: 'addition',
        debit: 281062,
        credit: 0,
        runningBalance: 475862,
      },
      {
        id: 'MOV-008-2',
        date: '2024-05-31',
        description: 'Cost of goods sold - dispatched',
        reference: 'COGS-MAY24',
        type: 'disposal',
        debit: 0,
        credit: 281062,
        runningBalance: 194800,
      },
      {
        id: 'MOV-008-3',
        date: '2024-05-31',
        description: 'Stock write-down - slow moving items',
        reference: 'JNL-2024-0147',
        type: 'adjustment',
        debit: 0,
        credit: 8380,
        runningBalance: 186420,
      },
    ],
    variance: 0,
    status: 'in_progress',
    lastUpdated: '2024-06-04T09:00:00+10:00',
    preparedBy: 'Olivia Nguyen',
    supportingSchedule: 'Inventory_Count_May2024.xlsx',
  },
]

// ─── Accrual Items ────────────────────────────────────────────────────────────

export const accrualItems: AccrualItem[] = [
  {
    id: 'ACC-001',
    description: 'Deloitte - Q4 audit services',
    supplier: 'Deloitte Touche Tohmatsu',
    accountCode: '6210',
    accountName: 'Professional Services',
    accrualDate: '2024-05-31',
    reversalDate: '2024-06-01',
    amount: 55000,
    status: 'active',
    journalRef: 'JNL-2024-0145',
    category: 'expense',
  },
  {
    id: 'ACC-002',
    description: 'Electricity - Ausgrid May usage (invoice not yet received)',
    supplier: 'Ausgrid Energy',
    accountCode: '6700',
    accountName: 'Utilities',
    accrualDate: '2024-05-31',
    reversalDate: '2024-06-01',
    amount: 4180,
    status: 'active',
    journalRef: 'JNL-2024-0145',
    category: 'expense',
  },
  {
    id: 'ACC-003',
    description: 'IT managed services - Telstra Business May invoice',
    supplier: 'Telstra Business',
    accountCode: '6220',
    accountName: 'IT & Software Subscriptions',
    accrualDate: '2024-05-31',
    reversalDate: '2024-06-01',
    amount: 8400,
    status: 'active',
    journalRef: 'JNL-2024-0145',
    category: 'expense',
  },
  {
    id: 'ACC-004',
    description: 'Cleaning services - Advance Building Services May',
    supplier: 'Advance Building Services',
    accountCode: '6350',
    accountName: 'Repairs & Maintenance',
    accrualDate: '2024-05-31',
    reversalDate: '2024-06-01',
    amount: 6250,
    status: 'active',
    journalRef: 'JNL-2024-0145',
    category: 'expense',
  },
  {
    id: 'ACC-005',
    description: 'ANZ term loan interest - May accrual',
    supplier: 'ANZ Banking Group',
    accountCode: '8000',
    accountName: 'Interest Expense',
    accrualDate: '2024-05-31',
    reversalDate: '2024-06-01',
    amount: 6840,
    status: 'active',
    journalRef: 'JNL-2024-0145',
    category: 'interest',
  },
  {
    id: 'ACC-006',
    description: 'Income tax provision - May 2024',
    supplier: 'Australian Taxation Office',
    accountCode: '9000',
    accountName: 'Income Tax Expense',
    accrualDate: '2024-05-31',
    reversalDate: '2024-06-01',
    amount: 19053,
    status: 'active',
    journalRef: 'JNL-2024-0145',
    category: 'tax',
  },
  {
    id: 'ACC-007',
    description: 'Google Ads digital spend - unbilled impressions May',
    supplier: 'Google Australia Pty Ltd',
    accountCode: '6510',
    accountName: 'Advertising & Marketing',
    accrualDate: '2024-05-31',
    reversalDate: '2024-06-01',
    amount: 3800,
    status: 'active',
    journalRef: 'JNL-2024-0145',
    category: 'expense',
  },
  {
    id: 'ACC-008',
    description: 'April accrual - Ausgrid electricity (reversed June 1)',
    supplier: 'Ausgrid Energy',
    accountCode: '6700',
    accountName: 'Utilities',
    accrualDate: '2024-04-30',
    reversalDate: '2024-05-01',
    amount: 3920,
    status: 'reversed',
    journalRef: 'JNL-2024-0138',
    category: 'expense',
  },
]

// ─── Prepayment Items ─────────────────────────────────────────────────────────

export const prepaymentItems: PrepaymentItem[] = [
  {
    id: 'PRE-001',
    description: 'Business Pack Insurance - Annual Premium FY2024',
    supplier: 'Allianz Australia',
    accountCode: '1300',
    accountName: 'Prepayments',
    invoiceDate: '2023-07-01',
    invoiceRef: 'ALZ-2023-8842',
    totalAmount: 49500,
    startDate: '2023-07-01',
    endDate: '2024-06-30',
    monthlyAmortisation: 4125,
    amortisedToDate: 45375,
    remaining: 4125,
    status: 'active',
    category: 'insurance',
  },
  {
    id: 'PRE-002',
    description: 'Office Lease - Prepaid Rent Incentive Bond',
    supplier: 'GPT Group',
    accountCode: '1300',
    accountName: 'Prepayments',
    invoiceDate: '2022-10-01',
    invoiceRef: 'GPT-BOND-2022',
    totalAmount: 102600,
    startDate: '2022-10-01',
    endDate: '2025-09-30',
    monthlyAmortisation: 2850,
    amortisedToDate: 62700,
    remaining: 39900,
    status: 'active',
    category: 'rent',
  },
  {
    id: 'PRE-003',
    description: 'Microsoft 365 Business Premium - Annual Licence',
    supplier: 'Microsoft Australia',
    accountCode: '1300',
    accountName: 'Prepayments',
    invoiceDate: '2024-01-01',
    invoiceRef: 'MSFT-2024-00148',
    totalAmount: 18540,
    startDate: '2024-01-01',
    endDate: '2024-12-31',
    monthlyAmortisation: 1545,
    amortisedToDate: 7725,
    remaining: 10815,
    status: 'active',
    category: 'software',
  },
  {
    id: 'PRE-004',
    description: 'Salesforce CRM - Annual Subscription',
    supplier: 'Salesforce Australia Pty Ltd',
    accountCode: '1300',
    accountName: 'Prepayments',
    invoiceDate: '2024-02-01',
    invoiceRef: 'SF-INV-2024-0228',
    totalAmount: 28800,
    startDate: '2024-02-01',
    endDate: '2025-01-31',
    monthlyAmortisation: 2400,
    amortisedToDate: 9600,
    remaining: 19200,
    status: 'active',
    category: 'software',
  },
  {
    id: 'PRE-005',
    description: 'HVAC Service Contract - Annual Maintenance Agreement',
    supplier: 'Johnson Controls Australia',
    accountCode: '1300',
    accountName: 'Prepayments',
    invoiceDate: '2024-04-01',
    invoiceRef: 'JC-2024-MAI-0041',
    totalAmount: 9600,
    startDate: '2024-04-01',
    endDate: '2025-03-31',
    monthlyAmortisation: 800,
    amortisedToDate: 1600,
    remaining: 8000,
    status: 'active',
    category: 'maintenance',
  },
  {
    id: 'PRE-006',
    description: 'Business Travel Insurance - Annual Policy FY2023',
    supplier: 'QBE Insurance',
    accountCode: '1300',
    accountName: 'Prepayments',
    invoiceDate: '2023-07-01',
    invoiceRef: 'QBE-2023-TRV-0921',
    totalAmount: 4200,
    startDate: '2023-07-01',
    endDate: '2024-06-30',
    monthlyAmortisation: 350,
    amortisedToDate: 4200,
    remaining: 0,
    status: 'fully_amortised',
    category: 'insurance',
  },
]

// ─── Fixed Assets ─────────────────────────────────────────────────────────────

export const fixedAssets: FixedAsset[] = [
  {
    id: 'FA-001',
    assetCode: 'VEH-001',
    assetName: 'Toyota HiLux WorkMax 4x4 - Sales Fleet',
    category: 'vehicle',
    acquisitionDate: '2022-08-15',
    cost: 68400,
    residualValue: 15000,
    usefulLife: 5,
    depreciationMethod: 'diminishing_value',
    accumulatedDepreciation: 27360,
    netBookValue: 41040,
    monthlyDepreciation: 870,
    status: 'active',
  },
  {
    id: 'FA-002',
    assetCode: 'VEH-002',
    assetName: 'Ford Transit Van - Logistics',
    category: 'vehicle',
    acquisitionDate: '2021-03-01',
    cost: 52000,
    residualValue: 8000,
    usefulLife: 5,
    depreciationMethod: 'straight_line',
    accumulatedDepreciation: 38720,
    netBookValue: 13280,
    monthlyDepreciation: 733,
    status: 'active',
  },
  {
    id: 'FA-003',
    assetCode: 'EQP-001',
    assetName: 'CNC Machining Centre - Production Line A',
    category: 'equipment',
    acquisitionDate: '2020-06-30',
    cost: 285000,
    residualValue: 20000,
    usefulLife: 10,
    depreciationMethod: 'straight_line',
    accumulatedDepreciation: 138750,
    netBookValue: 146250,
    monthlyDepreciation: 2208,
    status: 'active',
  },
  {
    id: 'FA-004',
    assetCode: 'EQP-002',
    assetName: 'Industrial Forklift - Warehouse',
    category: 'plant',
    acquisitionDate: '2021-11-15',
    cost: 48500,
    residualValue: 5000,
    usefulLife: 8,
    depreciationMethod: 'diminishing_value',
    accumulatedDepreciation: 19200,
    netBookValue: 29300,
    monthlyDepreciation: 520,
    status: 'active',
  },
  {
    id: 'FA-005',
    assetCode: 'EQP-003',
    assetName: 'Production Line Equipment - May 2024 Addition',
    category: 'equipment',
    acquisitionDate: '2024-05-10',
    cost: 43800,
    residualValue: 3000,
    usefulLife: 7,
    depreciationMethod: 'straight_line',
    accumulatedDepreciation: 490,
    netBookValue: 43310,
    monthlyDepreciation: 490,
    status: 'active',
  },
  {
    id: 'FA-006',
    assetCode: 'COMP-001',
    assetName: 'Dell PowerEdge Server - IT Infrastructure',
    category: 'computer',
    acquisitionDate: '2022-01-20',
    cost: 32400,
    residualValue: 2000,
    usefulLife: 4,
    depreciationMethod: 'straight_line',
    accumulatedDepreciation: 24050,
    netBookValue: 8350,
    monthlyDepreciation: 633,
    status: 'active',
  },
  {
    id: 'FA-007',
    assetCode: 'COMP-002',
    assetName: 'Lenovo ThinkPad Fleet (15 units)',
    category: 'computer',
    acquisitionDate: '2023-02-01',
    cost: 39750,
    residualValue: 3975,
    usefulLife: 3,
    depreciationMethod: 'straight_line',
    accumulatedDepreciation: 14963,
    netBookValue: 24787,
    monthlyDepreciation: 997,
    status: 'active',
  },
  {
    id: 'FA-008',
    assetCode: 'FURN-001',
    assetName: 'Office Fitout - Level 4, 20 Martin Place',
    category: 'leasehold',
    acquisitionDate: '2022-10-01',
    cost: 142000,
    residualValue: 0,
    usefulLife: 10,
    depreciationMethod: 'straight_line',
    accumulatedDepreciation: 26483,
    netBookValue: 115517,
    monthlyDepreciation: 1183,
    status: 'active',
  },
  {
    id: 'FA-009',
    assetCode: 'INT-001',
    assetName: 'ERP System Implementation - SAP B1',
    category: 'intangible',
    acquisitionDate: '2021-07-01',
    cost: 185000,
    residualValue: 0,
    usefulLife: 7,
    depreciationMethod: 'straight_line',
    accumulatedDepreciation: 99107,
    netBookValue: 85893,
    monthlyDepreciation: 2202,
    status: 'active',
  },
  {
    id: 'FA-010',
    assetCode: 'FURN-002',
    assetName: 'Conference Room AV Equipment',
    category: 'furniture',
    acquisitionDate: '2019-09-01',
    cost: 28000,
    residualValue: 0,
    usefulLife: 5,
    depreciationMethod: 'straight_line',
    accumulatedDepreciation: 28000,
    netBookValue: 0,
    monthlyDepreciation: 0,
    status: 'fully_depreciated',
  },
]

// ─── Journal Entries ──────────────────────────────────────────────────────────

export const journalEntries: JournalEntry[] = [
  {
    id: 'JNL-2024-0145',
    type: 'accrual',
    period: 'May 2024',
    reference: 'JNL-2024-0145',
    date: '2024-05-31',
    description: 'May 2024 Month-End Accruals Bundle',
    preparedBy: 'James Hartley',
    status: 'posted',
    approvedBy: 'Michael Park',
    postedAt: '2024-06-01T09:05:44+10:00',
    lines: [
      {
        id: 'JL-0145-01',
        accountCode: '6210',
        accountName: 'Professional Services',
        description: 'Deloitte - Q4 audit accrual',
        debit: 55000,
        credit: 0,
        costCenter: 'G&A',
      },
      {
        id: 'JL-0145-02',
        accountCode: '6700',
        accountName: 'Utilities',
        description: 'Ausgrid electricity - May accrual',
        debit: 4180,
        credit: 0,
        costCenter: 'FACILITIES',
      },
      {
        id: 'JL-0145-03',
        accountCode: '6220',
        accountName: 'IT & Software Subscriptions',
        description: 'Telstra managed services - May accrual',
        debit: 8400,
        credit: 0,
        costCenter: 'IT',
      },
      {
        id: 'JL-0145-04',
        accountCode: '6350',
        accountName: 'Repairs & Maintenance',
        description: 'Advance Building Services - May accrual',
        debit: 6250,
        credit: 0,
        costCenter: 'FACILITIES',
      },
      {
        id: 'JL-0145-05',
        accountCode: '8000',
        accountName: 'Interest Expense',
        description: 'ANZ term loan interest accrual',
        debit: 6840,
        credit: 0,
        costCenter: 'FINANCE',
      },
      {
        id: 'JL-0145-06',
        accountCode: '6510',
        accountName: 'Advertising & Marketing',
        description: 'Google Ads unbilled spend accrual',
        debit: 3800,
        credit: 0,
        costCenter: 'MARKETING',
      },
      {
        id: 'JL-0145-07',
        accountCode: '2110',
        accountName: 'Accrued Liabilities',
        description: 'May accruals - contra liability',
        debit: 0,
        credit: 84470,
        costCenter: 'FINANCE',
      },
    ],
    totalDebit: 84470,
    totalCredit: 84470,
    isBalanced: true,
  },
  {
    id: 'JNL-2024-0146',
    type: 'depreciation',
    period: 'May 2024',
    reference: 'JNL-2024-0146',
    date: '2024-05-31',
    description: 'May 2024 Depreciation & Amortisation',
    preparedBy: 'Olivia Nguyen',
    status: 'posted',
    approvedBy: 'Michael Park',
    postedAt: '2024-06-03T09:12:00+10:00',
    lines: [
      {
        id: 'JL-0146-01',
        accountCode: '7100',
        accountName: 'Depreciation & Amortisation',
        description: 'Monthly D&A charge - all assets',
        debit: 14280,
        credit: 0,
        costCenter: 'FINANCE',
      },
      {
        id: 'JL-0146-02',
        accountCode: '1510',
        accountName: 'Accumulated Depreciation',
        description: 'PP&E accumulated depreciation',
        debit: 0,
        credit: 12078,
        costCenter: 'FINANCE',
      },
      {
        id: 'JL-0146-03',
        accountCode: '1600',
        accountName: 'Intangible Assets - Software',
        description: 'Software amortisation - SAP B1',
        debit: 0,
        credit: 2202,
        costCenter: 'IT',
      },
    ],
    totalDebit: 14280,
    totalCredit: 14280,
    isBalanced: true,
  },
  {
    id: 'JNL-2024-0147',
    type: 'manual',
    period: 'May 2024',
    reference: 'JNL-2024-0147',
    date: '2024-05-31',
    description: 'Inventory write-down - slow moving stock',
    preparedBy: 'Sarah Chen',
    status: 'posted',
    approvedBy: 'Michael Park',
    postedAt: '2024-06-04T08:30:00+10:00',
    lines: [
      {
        id: 'JL-0147-01',
        accountCode: '5100',
        accountName: 'Cost of Goods Sold - Products',
        description: 'Write-down - slow moving inventory',
        debit: 8380,
        credit: 0,
        costCenter: 'WAREHOUSE',
      },
      {
        id: 'JL-0147-02',
        accountCode: '1200',
        accountName: 'Inventory - Finished Goods',
        description: 'Reduction in inventory carrying value',
        debit: 0,
        credit: 8380,
        costCenter: 'WAREHOUSE',
      },
    ],
    totalDebit: 8380,
    totalCredit: 8380,
    isBalanced: true,
  },
  {
    id: 'JNL-2024-0148',
    type: 'prepayment',
    period: 'May 2024',
    reference: 'JNL-2024-0148',
    date: '2024-05-31',
    description: 'May 2024 Prepayment Amortisation',
    preparedBy: 'Sarah Chen',
    status: 'posted',
    approvedBy: 'Michael Park',
    postedAt: '2024-06-03T11:30:00+10:00',
    lines: [
      {
        id: 'JL-0148-01',
        accountCode: '6600',
        accountName: 'Insurance',
        description: 'Allianz business insurance - monthly amortisation',
        debit: 4125,
        credit: 0,
        costCenter: 'G&A',
      },
      {
        id: 'JL-0148-02',
        accountCode: '6200',
        accountName: 'Rent & Occupancy',
        description: 'GPT prepaid rent - monthly amortisation',
        debit: 2850,
        credit: 0,
        costCenter: 'FACILITIES',
      },
      {
        id: 'JL-0148-03',
        accountCode: '6220',
        accountName: 'IT & Software Subscriptions',
        description: 'Microsoft 365 & Salesforce - monthly amortisation',
        debit: 3945,
        credit: 0,
        costCenter: 'IT',
      },
      {
        id: 'JL-0148-04',
        accountCode: '6350',
        accountName: 'Repairs & Maintenance',
        description: 'Johnson Controls HVAC contract - monthly amortisation',
        debit: 800,
        credit: 0,
        costCenter: 'FACILITIES',
      },
      {
        id: 'JL-0148-05',
        accountCode: '1300',
        accountName: 'Prepayments',
        description: 'Reduction in prepayment balance',
        debit: 0,
        credit: 11720,
        costCenter: 'FINANCE',
      },
    ],
    totalDebit: 11720,
    totalCredit: 11720,
    isBalanced: true,
  },
  {
    id: 'JNL-2024-0149',
    type: 'tax',
    period: 'May 2024',
    reference: 'JNL-2024-0149',
    date: '2024-05-31',
    description: 'Income Tax Provision - May 2024',
    preparedBy: 'James Hartley',
    status: 'posted',
    approvedBy: 'Michael Park',
    postedAt: '2024-06-04T08:00:00+10:00',
    lines: [
      {
        id: 'JL-0149-01',
        accountCode: '9000',
        accountName: 'Income Tax Expense',
        description: 'Income tax at 30% on taxable income',
        debit: 19053,
        credit: 0,
        costCenter: 'FINANCE',
      },
      {
        id: 'JL-0149-02',
        accountCode: '2200',
        accountName: 'Income Tax Payable',
        description: 'Tax liability - current portion',
        debit: 0,
        credit: 19053,
        costCenter: 'FINANCE',
      },
    ],
    totalDebit: 19053,
    totalCredit: 19053,
    isBalanced: true,
  },
  {
    id: 'JNL-2024-0150',
    type: 'reclass',
    period: 'May 2024',
    reference: 'JNL-2024-0150',
    date: '2024-05-31',
    description: 'Reclassification - redundancy payment to correct cost centre',
    preparedBy: 'James Hartley',
    status: 'draft',
    reversalDate: '2024-06-01',
    lines: [
      {
        id: 'JL-0150-01',
        accountCode: '6100',
        accountName: 'Wages & Salaries',
        description: 'Redundancy settlement - reclass from payroll run',
        debit: 18500,
        credit: 0,
        costCenter: 'HR',
      },
      {
        id: 'JL-0150-02',
        accountCode: '6100',
        accountName: 'Wages & Salaries',
        description: 'Redundancy settlement - reverse from SALES cost centre',
        debit: 0,
        credit: 18500,
        costCenter: 'SALES',
      },
    ],
    totalDebit: 18500,
    totalCredit: 18500,
    isBalanced: true,
  },
]
